all:
    # install pycocotools locally
	/home/pemfir/anaconda3/envs/comp_vis/bin/python setup.py build_ext --inplace
	rm -rf build

install:
	# install pycocotools to the Python site-packages
	/home/pemfir/anaconda3/envs/comp_vis/bin/python setup.py build_ext install
	rm -rf build